<?php
/**
 * Prompteg Cloud Backend - 1-Click Web Installer
 */
require_once __DIR__ . '/config.php';

$message = '';
$error = '';
$installed = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $dbHost = trim($_POST['db_host'] ?? DB_HOST);
    $dbName = trim($_POST['db_name'] ?? DB_NAME);
    $dbUser = trim($_POST['db_user'] ?? DB_USER);
    $dbPass = trim($_POST['db_pass'] ?? DB_PASS);
    $adminUser = trim($_POST['admin_user'] ?? 'admin');
    $adminPass = trim($_POST['admin_pass'] ?? 'admin1234');
    $apiKey = trim($_POST['api_key'] ?? 'prompteg_secret_key_2026');

    try {
        $dsn = "mysql:host={$dbHost};charset=utf8mb4";
        $pdo = new PDO($dsn, $dbUser, $dbPass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
        ]);

        // Create Database if not exists
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $pdo->exec("USE `{$dbName}`");

        // Load database.sql
        $sqlPath = __DIR__ . '/database.sql';
        if (file_exists($sqlPath)) {
            $sql = file_get_contents($sqlPath);
            // Execute queries
            $pdo->exec($sql);
        }

        // Update custom admin user and API key
        $passHash = password_hash($adminPass, PASSWORD_BCRYPT);
        $stmt = $pdo->prepare("
            INSERT INTO `admin_users` (`id`, `username`, `password_hash`, `email`) 
            VALUES (1, ?, ?, 'admin@prompteg.ai') 
            ON DUPLICATE KEY UPDATE `username` = VALUES(`username`), `password_hash` = VALUES(`password_hash`)
        ");
        $stmt->execute([$adminUser, $passHash]);

        // Set API key
        $stmtKey = $pdo->prepare("
            INSERT INTO `settings` (`key_name`, `value_text`, `description`) 
            VALUES ('api_secret_key', ?, 'Mobile Sync Secret Key') 
            ON DUPLICATE KEY UPDATE `value_text` = VALUES(`value_text`)
        ");
        $stmtKey->execute([$apiKey]);

        // Write config.php
        $configContent = "<?php\n";
        $configContent .= "// Auto-generated by Prompteg Installer\n";
        $configContent .= "define('DB_HOST', " . var_export($dbHost, true) . ");\n";
        $configContent .= "define('DB_PORT', '3306');\n";
        $configContent .= "define('DB_NAME', " . var_export($dbName, true) . ");\n";
        $configContent .= "define('DB_USER', " . var_export($dbUser, true) . ");\n";
        $configContent .= "define('DB_PASS', " . var_export($dbPass, true) . ");\n";
        $configContent .= "define('API_SECRET_KEY', " . var_export($apiKey, true) . ");\n";
        $configContent .= "define('SESSION_NAME', 'prompteg_admin_session');\n";
        $configContent .= "define('ADMIN_TITLE', 'PROMPTEG AI // MASTER CLOUD ADMIN');\n";
        $configContent .= "define('APP_VERSION', '2.0.0');\n";
        $configContent .= "define('APP_ENV', 'production');\n";

        file_put_contents(__DIR__ . '/config.php', $configContent);

        $installed = true;
        $message = "Database & Admin setup completed successfully!";
    } catch (Exception $e) {
        $error = "Installation failed: " . $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Prompteg AI - Cloud Database Installer</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600;800&display=swap" rel="stylesheet">
  <style>
    body { font-family: 'JetBrains Mono', monospace; }
  </style>
</head>
<body class="bg-gray-950 text-gray-100 min-h-screen flex items-center justify-center p-4">
  <div class="max-w-xl w-full bg-gray-900 border border-orange-500/40 rounded-2xl p-8 shadow-2xl shadow-orange-950/40">
    <div class="flex items-center space-x-3 mb-6">
      <div class="w-10 h-10 rounded-xl bg-orange-600 flex items-center justify-center text-black font-black text-xl">P</div>
      <div>
        <h1 class="text-xl font-extrabold text-orange-500 tracking-wider">PROMPTEG AI HUB</h1>
        <p class="text-xs text-gray-400">1-Click MySQL & Backend Auto-Installer</p>
      </div>
    </div>

    <?php if ($installed): ?>
      <div class="bg-emerald-950/80 border border-emerald-500/50 p-6 rounded-xl mb-6">
        <h2 class="text-emerald-400 font-bold text-lg mb-2">🎉 Installation Complete!</h2>
        <p class="text-sm text-gray-300 mb-4"><?= htmlspecialchars($message) ?></p>
        <div class="space-y-2 text-xs bg-gray-900/90 p-4 rounded-lg border border-gray-800">
          <div><strong class="text-orange-400">Admin URL:</strong> <a href="admin/login.php" class="text-cyan-400 underline">./admin/login.php</a></div>
          <div><strong class="text-orange-400">Sync API URL:</strong> <code class="text-emerald-300"><?= (isset($_SERVER['HTTPS']) ? 'https://' : 'http://') . $_SERVER['HTTP_HOST'] . dirname($_SERVER['REQUEST_URI']) . '/api/sync.php' ?></code></div>
          <div><strong class="text-orange-400">API Secret Key:</strong> <code class="text-amber-300"><?= htmlspecialchars($_POST['api_key'] ?? '') ?></code></div>
        </div>
        <div class="mt-6 flex gap-3">
          <a href="admin/login.php" class="flex-1 text-center bg-orange-500 hover:bg-orange-600 text-black font-black py-3 rounded-lg text-sm transition">GO TO ADMIN PANEL</a>
        </div>
      </div>
    <?php else: ?>
      <?php if ($error): ?>
        <div class="bg-rose-950/80 border border-rose-500/50 text-rose-300 text-xs p-4 rounded-xl mb-6">
          <strong>Error:</strong> <?= htmlspecialchars($error) ?>
        </div>
      <?php endif; ?>

      <form method="POST" class="space-y-4">
        <div class="border-b border-gray-800 pb-3 mb-2">
          <h2 class="text-sm font-bold text-cyan-400 uppercase tracking-wider">1. MySQL Database Configuration</h2>
        </div>

        <div>
          <label class="block text-xs font-semibold text-gray-400 mb-1">Database Host</label>
          <input type="text" name="db_host" value="localhost" class="w-full bg-gray-950 border border-gray-800 focus:border-orange-500 rounded-lg px-3 py-2 text-sm text-gray-100 outline-none" required>
        </div>

        <div>
          <label class="block text-xs font-semibold text-gray-400 mb-1">Database Name</label>
          <input type="text" name="db_name" value="prompteg_db" class="w-full bg-gray-950 border border-gray-800 focus:border-orange-500 rounded-lg px-3 py-2 text-sm text-gray-100 outline-none" required>
        </div>

        <div class="grid grid-cols-2 gap-3">
          <div>
            <label class="block text-xs font-semibold text-gray-400 mb-1">DB Username</label>
            <input type="text" name="db_user" value="root" class="w-full bg-gray-950 border border-gray-800 focus:border-orange-500 rounded-lg px-3 py-2 text-sm text-gray-100 outline-none" required>
          </div>
          <div>
            <label class="block text-xs font-semibold text-gray-400 mb-1">DB Password</label>
            <input type="password" name="db_pass" placeholder="Empty if local" class="w-full bg-gray-950 border border-gray-800 focus:border-orange-500 rounded-lg px-3 py-2 text-sm text-gray-100 outline-none">
          </div>
        </div>

        <div class="border-b border-gray-800 pb-3 pt-4 mb-2">
          <h2 class="text-sm font-bold text-cyan-400 uppercase tracking-wider">2. Web Admin Credentials</h2>
        </div>

        <div class="grid grid-cols-2 gap-3">
          <div>
            <label class="block text-xs font-semibold text-gray-400 mb-1">Admin Username</label>
            <input type="text" name="admin_user" value="admin" class="w-full bg-gray-950 border border-gray-800 focus:border-orange-500 rounded-lg px-3 py-2 text-sm text-gray-100 outline-none" required>
          </div>
          <div>
            <label class="block text-xs font-semibold text-gray-400 mb-1">Admin Password</label>
            <input type="text" name="admin_pass" value="admin1234" class="w-full bg-gray-950 border border-gray-800 focus:border-orange-500 rounded-lg px-3 py-2 text-sm text-gray-100 outline-none" required>
          </div>
        </div>

        <div>
          <label class="block text-xs font-semibold text-gray-400 mb-1">Mobile API Secret Key</label>
          <input type="text" name="api_key" value="prompteg_secret_key_2026" class="w-full bg-gray-950 border border-gray-800 focus:border-orange-500 rounded-lg px-3 py-2 text-sm text-amber-400 outline-none" required>
          <p class="text-[10px] text-gray-500 mt-1">You will enter this key in your Android App's Admin Hub to authenticate sync requests.</p>
        </div>

        <button type="submit" class="w-full bg-orange-500 hover:bg-orange-600 text-black font-extrabold py-3.5 rounded-xl text-sm transition tracking-wider mt-4">
          INSTALL & INITIALIZE PROMPTEG BACKEND
        </button>
      </form>
    <?php endif; ?>
  </div>
</body>
</html>
